New "Admin API and Stats API Access Token"
mulesoft/docs-mq pull request #11
Opened 2018-10-23 07:47 UTC by george-hoffer

2018-10-23 15:46 UTC, fededonna requested changes

2018-10-23 15:46 UTC, fededonna commented on modules/ROOT/pages/mq-apis.adoc
> +* The access token for any MQ API has a default time to live (TTL) of 180 minutes. This is the same TTL that users get when they log into the Anypoint Platform. The TTL is set in the Access Managemen
I'm not sure that access tokens for broker have a ttl of 180 minutes. Can you verify this with Authentication Server? Also ttl for those tokens can not be set in the ui.

2018-10-23 15:46 UTC, fededonna commented on modules/ROOT/pages/mq-apis.adoc
> +To get the Broker API access token:
I'm not the best English speaker but I think "the" in front of the broker is not necessary.

2018-10-23 15:46 UTC, fededonna commented on modules/ROOT/pages/mq-apis.adoc
> +For the Admin API and Stats API, get the access token from the Anypoint
same here

2018-10-23 23:17 UTC, jjayakumaran requested changes

2018-10-23 23:17 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +=== Set Studio for API Access
setup?

2018-10-23 23:17 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +=== Create a FIFO Queue in the Admin API
why did we get rid of portal? 
should be reverted or rephrased to **Create a FIFO Queue using Admin API**

2018-10-23 23:17 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +In the Broker API, click Download to download the RAML or the API as a Mule Plugin.
please add page or portal after Broker API.

2018-10-24 03:54 UTC, jjayakumaran approved these changes

2018-10-24 03:59 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +To get the Broker API access token:
The sentence is correct. The article "the" refers to "token".

2018-10-24 04:01 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +For the Admin API and Stats API, get the access token from the Anypoint
Need to have the "the" article per "the ... API" and for "the ... token".

2018-10-24 04:09 UTC, fededonna commented
LGTM

2018-10-24 04:12 UTC, fededonna approved these changes

2018-10-24 04:12 UTC, merged