W-11227823 intelligent message routing
mulesoft/docs-mq pull request #113
Opened 2022-07-23 01:16 UTC by hannanelson

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2022-07-29 06:22 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +You can use the Admin API to create these routing rules.
I think "routing rule" doesn't make it clear that the rule is for conditionally routing a message. Can we replace it with "message routing rule" instead? (throughout the doc)

2022-07-29 06:23 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +To route messages published to an exchange to specific queues,
It might be better to reword this from a queue's perspective i.e., if a queue wants to receive only a subset of messages published to the exchange...

2022-07-29 06:31 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +  -d "{\n  \"routingRules\": [\n    {\n      \"propertyName\": \"itemCategory\",\n      \"propertyType\": \"STRING\",\n      \"matcherType\": \"EQ/PREFIX\",\n      \"value\": premium\n    }\n  ]\n}"
matcherType can either be "EQ" or "PREFIX".. "EQ/PREFIX" is not a valid matcher type. Looks like I need to update the RAML spec as well because when I say matcherType: "EQ/PREFIX" in the spec, it could cause the same confusion for customers.

2022-07-29 06:35 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +If the value of the `itemCategory` property on the message matches `premium`,
If message published to the "purchases" exchange has a property or header with the name "itemCategory" and value "premium", the above message routing rule defined on the binding routes the message to the "premiumPurchases" queue.

2022-07-29 06:41 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +-d '{ \
Can we use this payload to make it clear that we allow sending routing properties both in "headers" and "properties" sections of the payload:
 { \
  "properties": {
    "itemCategory": "premium"
  },
  "headers": {
    "itemSize": "large"
  },
  "body": "This is a message payload"
}

2022-07-29 06:46 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
Product wants to market this feature as "Intelligent Message Routing". Should we call this "Intelligent Message Routing Rules" or "Configure Intelligent Message Routing Rules" ?

2022-07-29 06:50 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +You can publish messages to an exchange and define rules
"property or header" instead of "property"

2022-07-29 06:53 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If an exchange has more than 10 queues, you cannot use message filtering.
How about "If an exchange has more than 10 queue bindings, you cannot use message routing capabilities" ?

2022-07-29 06:55 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +** Total number of headers and properties is fewer than 500.
This 500 limit also includes operational headers like messageId, createdTimestamp that Anypoint MQ creates. We should document this so that customers can leave some buffer for these headers and don't expect to have all 500 available for their use

2022-07-29 06:57 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If an exchange has more than 10 queues, you cannot use message filtering.
We should also document this 10 bindings limit here: https://github.com/mulesoft/docs-mq/pull/107/files#diff-e75c33ddbc5485f2d6a452249880e5ac9aa2d361dc176cd76e90fe4668847e7cR2

2022-07-29 06:58 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Restrictions
We should add a note that additions or changes to a message routing rule will take up to 15 minutes to fully take effect. Not sure if Restrictions section is the right place for it

2022-07-29 07:01 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
Need to find the right place to document that for exchanges, we will only encrypt the message body whereas for queues we will encrypt headers, properties and body: https://mulesoft.slack.com/archives/C03EDUK9E/p1658945078703969?thread_ts=1658934782.770999&cid=C03EDUK9E

Please let me know if you have any questions regarding this. We can sync up offline.

2022-07-29 07:07 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Anypoint MQ supports message filtering for messages that meet the follow size criteria:
We should add a note somewhere that we won't reject a message published to exchange whose headers/properties don't satisfy the below conditions, but instead we will just not consider these properties while evaluating the message against routing rules configured on the bindings.
https://salesforce.quip.com/xtOYA1rD9TBE#temp:C:WSPc9b67f35e99285569a0889fba

2022-07-29 07:12 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If a message doesn't meet these criteria, Anypoint MQ logs that the message is not eligible for filtering and delivers the message to a queue without filtering.
We can skip the logging part because that's internal implementation that will help us with debugging and might not be relevant information for end users.

Needs refining but this should be something along the lines of "If a message doesn't meet these criteria, Anypoint MQ will not reject the message published to the exchange. It will just not consider these properties while evaluating the message against routing rules configured on the bindings."
Reason: 
Technically, the message could get delivered to a queue which has filtering rules as well. Eg: If the rule is "property1" EXISTS = false and the property in the message is > 215KB size, we just ignore these properties; filtering logic is looking for "property1" and since message doesn't have the property (because we ignored it for filtering purposes), the message will get routed to the queue.

2022-07-29 07:14 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +        "ttl" : 5,
Let me confirm with Shashi and get back to you on this numeric attribute. I want to confirm if we want to allow numeric attributes for beta customers or just string attributes.

2022-07-29 18:40 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +You can use the Admin API to create these routing rules.
done

2022-07-29 19:00 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +To route messages published to an exchange to specific queues,
What about:
To route a subset of the messages that are published to an exchange to specific queues,

2022-07-29 19:03 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +  -d "{\n  \"routingRules\": [\n    {\n      \"propertyName\": \"itemCategory\",\n      \"propertyType\": \"STRING\",\n      \"matcherType\": \"EQ/PREFIX\",\n      \"value\": premium\n    }\n  ]\n}"
Clarified.

2022-07-29 19:16 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
done

2022-07-29 19:16 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +-d '{ \
done

2022-07-29 19:29 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +        "ttl" : 5,
We can just take it out for the beta...

2022-07-29 19:53 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Restrictions
Added to API topic. When it's in the UI, we can add it there too.

2022-07-29 19:54 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If an exchange has more than 10 queues, you cannot use message filtering.
gotcha

2022-07-29 21:07 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
ok

2022-07-29 21:13 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If a message doesn't meet these criteria, Anypoint MQ logs that the message is not eligible for filtering and delivers the message to a queue without filtering.
What about:
If a message doesn’t meet these criteria, Anypoint MQ publishes the message to the exchange but ignores the properties when evaluating the message against the routing rules configured on the bindings.

2022-07-29 21:16 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
Added in various places.

2022-08-04 02:45 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +==== Create Routing Rules
"Create Message Routing Rules" instead of "Create Routing Rules"

2022-08-04 02:46 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +  -d "{\n  \"routingRules\": [\n    {\n      \"propertyName\": \"itemCategory\",\n      \"propertyType\": \"STRING\",\n      \"matcherType\": \"EQ\",\n      \"value\": premium\n    }\n  ]\n}"
premium needs to be enclosed within \" as well since it's a string property value.

2022-08-04 02:50 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +To change an existing routing rule, submit another `PUT` with the new message routing rule configuration.
Can we also mention that a PUT request will replace the existing routing rule on the binding with the new rule.

2022-08-04 02:51 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +Any changes or additions to a message routing rule can take up to 15 minutes to take effect.
Any new rule created will also take up to 15 minutes to take effect. If "changes or additions" implies creation as well, the above looks good. Otherwise, we need to update it to be more explicit.

2022-08-04 02:53 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +xref:mq-routing-rules.adoc#intelligent-routing-limitations[Limitations].
Should we call this "limitations" or "restrictions"? To me, limitations sounds like something we could not implement and restrictions sounds like something we're enforcing :)

2022-08-04 02:54 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +[source]
This will point to the RAML once I have it published?

2022-08-04 02:56 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +For information on the supported properties and attributes for `routingRules`,
How about "For information on the supported payload for `routingRules`" ? 
Since the entire payload is talking about properties, if we use the word "attributes", I'm wondering if customers might misinterpret it for something else.

2022-08-04 02:59 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +      "matcherType" : "EQ/PREFIX",
Is this going to show up on the UI? If yes, we should have just "EQ" or just "PREFIX"

2022-08-04 03:01 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +[NOTE]
We should add another note here that any bindings that don't have message routing rules configured will continue to receive all messages from the exchange (same behavior as before).

2022-08-04 03:03 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +For information about the message filtering limitations, see
"message routing rule" instead of "message filtering".
Same comment regarding "limitations". If limitations is a commonly used word in other docs as well, we can leave it as is.

2022-08-04 03:08 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +To route messages published to an exchange to specific queues,
That sounds good.

2022-08-04 03:13 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If a message doesn't meet these criteria, Anypoint MQ logs that the message is not eligible for filtering and delivers the message to a queue without filtering.
This sounds good. We should also add a note that we are ignoring the properties/headers just for the purpose of filtering, but they will still be published to the exchange. Otherwise, customers might think that we will not send these properties to the exchange.

2022-08-04 03:13 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +        "ttl" : 5,
Yes that would be better. Safe to include only strings for the beta documentation.

2022-08-04 05:55 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
How about "Configure Routing Rules on Message Exchanges" ? The other pages are called "Configure Queues", "Configure Client Apps", "Configure Message Exchanges".. so this aligns with the other pages as well.
When message is published to an exchange, it gets routed to the bound queues anyway. So, "Routing Messages to Queues Bound to an Exchange" might not tell customers that this is providing additional functionality on top of exchanges.

2022-08-04 06:07 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +Anypoint MQ includes the ability to create _intelligent message routing rules_ to control where to route messages published to an exchange.
hmm this one is tricky.. it's not "where to route messages published to an exchange" because we know where to publish - it's always the bindings on the exchange. The feature is more about "which subset of messages to forward to a specific binding on the exchange". Maybe you can reword this better :)

2022-08-04 06:10 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +When you publish messages to an exchange, the message routing rules
Before this sentence, we should explain that user can configure a message routing rule per binding on the exchange. That way we describe the entire flow - create rule on the binding, publish message to the exchange, exchange evaluates whether a binding gets the message based on the rule defined on the binding. If there is no rule on a binding, the message is forwarded to the binding.

2022-08-04 06:12 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +route messages to specific queues only if the message includes
How about "the message routing rules route a message to a queue only if the message includes a property or header that matches the rule" ?

2022-08-04 06:18 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +. Specify filtering criteria by defining properties in the message.
We should document that the rule be evaluated against all "headers" and "properties" in the message.

2022-08-04 06:19 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Route Messages to a Queue that is Bound to an Exchange
How about "Publish Message with Routing Properties" ?

2022-08-04 06:20 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If an exchange has more than 10 queue bindings, you cannot use intelligent message routing.
"you cannot configure message routing rules" ?

2022-08-04 06:22 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Each message routing rule can include one property-value pair.
How about "A message routing rule can be configured only on one property" ?

2022-08-04 06:24 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Total number of headers and properties is fewer than 500.
There's one more constraint here.
Maximum total size of headers and properties is 215 KB.

2022-08-04 06:26 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +Anypoint MQ supports message routing rules with the following limitations:
One more limitation to add:
Creating or modifying a message routing rule requires up to 15 minutes to fully take effect.

This is not really a limitation but it's better to document all the caveats at one place.

2022-08-04 17:15 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
What about this?

2022-08-04 17:40 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +      "matcherType" : "EQ/PREFIX",
This is commented out. It's a different (and easier to read) format. Just wondering if we want to use it instead.

2022-08-04 17:41 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +xref:mq-routing-rules.adoc#intelligent-routing-limitations[Limitations].
Good point. Let's use "Requirements and Restrictions" instead.

2022-08-04 17:45 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +For information about the message filtering limitations, see
This is the section on message headers, not rules...

2022-08-04 18:08 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
What about:
Configuring Rules on Message Exchanges to Route Messages

2022-08-04 18:19 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +If a message doesn't meet these criteria, Anypoint MQ logs that the message is not eligible for filtering and delivers the message to a queue without filtering.
Yes, "publishes the message to the exchange".

2022-08-04 18:23 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Each message routing rule can include one property-value pair.
except that's passive voice...

2022-08-06 02:38 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Routing Messages to Queues Bound to an Exchange
Sounds good.

2022-08-06 02:48 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +a property or header that matches a rule.
Should it be "matches the rule" since we're referring to just one rule throughout the sentence?

2022-08-06 02:52 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +** Maximum total size of headers and properties is 215 KB.
This should go in the section below. 215 KB is a constraint while publishing the message.

2022-08-06 02:57 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Maximum size of headers and property names is 180 bytes.
We can remove this one. While publishing the message, as long as the total number of headers and properties is < 500 and total size is < 215 KB, the headers and properties will be considered for filtering decisions.

2022-08-06 03:01 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +Anypoint MQ supports message filtering for messages that meet the following criteria:
There is room for misinterpretation here I think. If number of headers and properties are more than 500, the message will still be evaluated against the routing rule but it's just that the headers and properties will not be considered for the decision.
Eg: If the rule is "purchaseType" EXISTS false (user is saying they want to only allow messages that don't have the property name "purchaseType")
If a message published to the exchange has 501 properties, we ignore all the headers and properties for filtering decision. So from filtering point of view, this message doesn't have any headers and properties.. and user is saying they want the message forwarded if it doesn't have "purchaseType" property. So this message will get forwarded to the queue.
So, technically, filtering is still supported for the message. This is tricky to document :)

2022-08-06 03:02 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Each message routing rule can include one property-value pair.
What you have now looks good to me :)

2022-08-31 02:23 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +/organizations/ORGANIZATION_ID/environments/ENVIRONMENT_ID/regions/REGION_ID/bindings/exchanges/EXCHANGE_ID/queues/QUEUE_ID/routingRules
Hi @hannanelson , we decided to change the API path from "/routingRules" to "/rules/routing" after looking at some best practices. Would you be able to update it here and in the curl command as well. Thank you!

2022-09-06 16:24 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +/organizations/ORGANIZATION_ID/environments/ENVIRONMENT_ID/regions/REGION_ID/bindings/exchanges/EXCHANGE_ID/queues/QUEUE_ID/routingRules
@GouthamiKondakindi - does this option remain the same? 
`-d "{\n  \"routingRules\":`

2022-09-06 19:04 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +/organizations/ORGANIZATION_ID/environments/ENVIRONMENT_ID/regions/REGION_ID/bindings/exchanges/EXCHANGE_ID/queues/QUEUE_ID/routingRules
@hannanelson yes, the API payload remains the same.

2022-09-15 21:32 UTC, GouthamiKondakindi commented on modules/ROOT/pages/_partials/mq-faq.adoc
> +Anypoint MQ encrypts the entire payload, including the `headers`, `properties`, and `body`, of messages sent to queues.
@hannanelson After discussion with the team, we decided to change this to
`Anypoint MQ encrypts only the message body.  headers and properties of messages sent to exchanges and queues are not encrypted.`
That way, if we need to stop encrypting headers and properties for queues as well, we can do it since we never documented that we encrypt them in the first place :)

2022-10-06 22:49 UTC, hannanelson commented on modules/ROOT/pages/_partials/mq-faq.adoc
> +Anypoint MQ encrypts the entire payload, including the `headers`, `properties`, and `body`, of messages sent to queues.
Updated

2022-10-10 18:22 UTC, danieldatri requested changes

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-apis.adoc
> +-H "Postman-Token: 42544254-4254-4254-42544254-425442544254" \
I should delete all these lines with Postman-Token headers

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Create or Change a Message Routing Rule
@hannanelson @GouthamiKondakindi Do we have somewhere the table with Property Name and matchers explaining what each of them is with Example values? I remember is in the RAML but could be a good idea to add it here too.
What do you think?

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-exchanges.adoc
>  FIFO does not support the use of a message exchange. Similarly, FIFO queues cannot be bound to a message exchange.
@hannanelson @GouthamiKondakindi 
Since we are going to support FIFO exchanges soon. I will change this line for something like:
in order to maintain the order of the messages Routing Rules are not working on FIFO destinations.

This way we don't need to remember to change this line in the future when we release FIFO exchanges

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-queues.adoc
>  == Send a Message to a Queue
@hannanelson @GouthamiKondakindi I would add somewhere here something like **How to check properties on the messages** and the link to the message browser and the detail panel of each message where it shows the properties.

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +image::mq-exchange-create-routing-rule.png["Create Routing Rule page"]
We added a change on this modal. Now we have the following warning.
![image](https://user-images.githubusercontent.com/6400379/194929369-3b099735-48d2-48b6-8c6a-a22c870a377c.png)

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +image::mq-exchange-create-routing-rule.png["Create Routing Rule page"]
The same on the Edit

2022-10-10 18:22 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Requirements and Restrictions
I think we should add here what are the characters allowed on the property values for routing rules:
a-z, A-Z, 0-9, '(', ')', '@', '!', '&', '|', '#', '$', '%', whitespace, hyphen(-), underscore(_), colon(;), semi-colon(:), comma(,), period(.), single-quote(')

What do you think @GouthamiKondakindi ?

2022-10-10 22:44 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Create or Change a Message Routing Rule
https://beta.docs.mulesoft.com/beta-mq/mq/mq-routing-rules#matcher-type

2022-10-10 23:34 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Requirements and Restrictions
Elsewhere, we say: 
User property names can contain up to 42 alphanumeric characters (a-z, A-Z, 0-9), periods (.), hyphens (-), and colons (:). They cannot contain spaces or other characters.

2022-10-10 23:53 UTC, danieldatri requested changes

2022-10-10 23:53 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Requirements and Restrictions
Ok. Let me clarify because YES. It is confuse.
1- We have that validation in the message sender when you add a property but:
     1.a - The properties and values you send there are not necessarily to test the routing rules you can send any property and value just for testing an internal logic on your application.
     1.b - Saying this we removed the validation you mentioned from the property value on the message sender (you can check this on qax). (of course if you choose property type number it will validate you can only send numbers).

2- We found that for routing rules there are some characters that was causing errors on AWS. and we added the restrictions I mentioned above to both backend and UI.
So...that's why I say that one restriction for routing beside the ones you mentioned should be the characters you can use on the value.

2022-10-10 23:53 UTC, danieldatri commented on modules/ROOT/pages/mq-exchanges.adoc
> +image::mq-tutorial-message-sender-user-props.png["Add User Properties toggle in the Message Sender page"]
Another small change that we made to this section. Since we now have the possibility to send String or number.
we you add property number the pill is grey and blue for string to show in a visual way when you have numbers or strings.

![image](https://user-images.githubusercontent.com/6400379/194968945-bfa9b32b-d777-43b6-a6d6-5ddc522e197e.png)

2022-10-11 00:01 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +== Requirements and Restrictions
One more important think we should clarify and is IMPORTANT to avoid problems in the future. The decimal notation accepted for numbers is period ( . ) not comma ( , ) . This apply to the validation of the property value on the message sender and the property value of the routing rule.

2022-10-11 01:39 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-exchanges.adoc
> +To maintain message order, FIFO queues don't support message routing rules.
We should remove this. Once FIFO Exchanges feature is available, routing rules will be supported on FIFO Exchanges as well.

2022-10-11 01:44 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-exchanges.adoc
> +[NOTE]
The UI removed all validations on user properties. So this Note and the above line "include::partial$mq-user-props.adoc[tag=mquserprops]" should be removed.

@danieldatri can you please confirm

2022-10-11 01:50 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +To route a subset of the messages that are published to an exchange to a specific queue,
How about "Use the Admin API to create message routing rules on the binding between the exchange and the queue. This will route a subset of the messages that are published to an exchange to the queue associated with the binding" ?

2022-10-11 01:52 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-apis.adoc
> +see this endpoint in the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-admin/[Anypoint MQ Admin API]:
The RAML spec is published to exchange now. So, this URL can now be updated to https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-admin/minor/1.0/console/method/%23741/

We can remove line 156 as well since the above URL will take the user to the right API in the doc

2022-10-11 01:56 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +To route a subset of the messages that are published to an exchange to a specific queue,
The primary user goal is to route the messages. To do it, you create the rules.

2022-10-11 01:58 UTC, GouthamiKondakindi commented on modules/ROOT/pages/_partials/mq-user-props.adoc
> +User property names can contain up to 42 alphanumeric characters (a-z, A-Z, 0-9) and punctuation (. - :). They cannot contain spaces or other characters.
Is there room for misinterpretation here? Will user assume all punctuation characters are allowed?

2022-10-11 02:01 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-queues.adoc
>  include::partial$mq-user-props.adoc[tag=mquserprops]
Once @danieldatri confirms the UI behavior, we need to remove this line if the UI doesn't enforce any restrictions on special characters for property values now.

2022-10-11 02:05 UTC, hannanelson commented on modules/ROOT/pages/_partials/mq-user-props.adoc
> +User property names can contain up to 42 alphanumeric characters (a-z, A-Z, 0-9) and punctuation (. - :). They cannot contain spaces or other characters.
You don't think the parenthetical is enough?

2022-10-11 02:05 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Specify the property name and value to match.
We have restrictions on special characters allowed for property values. The UI shows this as a warning message. Is that enough or should we document it here as well?
![Screen Shot 2022-10-10 at 7 04 39 PM](https://user-images.githubusercontent.com/5511294/194980823-dcf690f7-1387-4e68-90e2-2e56129b3ce9.png)

2022-10-11 02:06 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +. Click *Create Routing Rule*.
The text on the button changed to "Add Rule" now instead of "Create Routing Rule"

2022-10-11 02:07 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +. Click *Edit Routing Rule*.
The text on the button changed to "Save Rule" now instead of "Edit Routing Rule"

2022-10-11 02:08 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> +For information on using the Anypoint Admin API to manage message routing rules, see
"Anypoint MQ Admin API" instead of "Anypoint Admin API" ?

2022-10-11 02:12 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-tutorial.adoc
>  include::partial$mq-user-props.adoc[tag=mquserprops]
Same comment. Should be removed if the UI no longer enforces restrictions on special characters allowed for property names/values

2022-10-11 02:13 UTC, GouthamiKondakindi commented on modules/ROOT/pages/_partials/mq-user-props.adoc
> +User property names can contain up to 42 alphanumeric characters (a-z, A-Z, 0-9) and punctuation (. - :). They cannot contain spaces or other characters.
Looks good to me but I'm not sure if that's because I already know what characters are allowed :)

2022-10-11 02:22 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Configure Rules on Message Exchanges to Route Messages
@hannanelson Where would be a right place to document this? It's important for customers to know this.

MQ Connector currently doesn't support publishing numeric value for properties. Any numbers will be converted to strings and sent to MQ Backend. A new version of Connector will be released this week to add support for numbers.

If user creates routing rule on a numeric property value, they need to use the latest version of MQ Connector so that they can publish numeric values in properties. Otherwise, older Connector versions will send the property values as strings and the messages won't match the routing rule, so the queue will stop receiving messages.

2022-10-11 04:40 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Specify the property name and value to match.
That message is wonky - some of the marks have their words and there should be spaces between the words and ().

2022-10-11 04:59 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Configure Rules on Message Exchanges to Route Messages
Maybe a note [here](https://beta.docs.mulesoft.com/beta-mq/mq/mq-routing-rules#matcher-type)? And in the release notes.

2022-10-11 17:05 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Specify the property name and value to match.
@hannanelson Can you please send me here what is the proper message we should put there?
Thanks

2022-10-11 17:06 UTC, danieldatri commented on modules/ROOT/pages/mq-queues.adoc
>  include::partial$mq-user-props.adoc[tag=mquserprops]
@GouthamiKondakindi I mentioned that here
https://github.com/mulesoft/docs-mq/pull/113/files#r991705764

2022-10-11 17:19 UTC, danieldatri commented on modules/ROOT/pages/mq-exchanges.adoc
> +[NOTE]
Yes....we removed the validations for property names and values (Except when you choose property type number, we validate the value is a number).

2022-10-11 17:22 UTC, danieldatri commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Configure Rules on Message Exchanges to Route Messages
@GouthamiKondakindi @hannanelson I think we should add that here
https://beta.docs.mulesoft.com/beta-mq/mq/mq-connectors#connectors::anypoint-mq/3.x/anypoint-mq-connector.adoc

is this change going to be on the connector 4.x among with the change to Authorize directly against Auth Service?

2022-10-11 21:43 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> +* Specify the property name and value to match.
I would like to leave it in the docs for folks who aren't using the UI.

Property values for routing rules can contain whitespace, alphanumeric (a-z, A-Z, 0-9), and punctuation (@ ! & | # $ % - _ : ; , . ') characters.

2022-10-11 21:44 UTC, hannanelson commented on modules/ROOT/pages/_partials/mq-user-props.adoc
> +User property names can contain up to 42 alphanumeric characters (a-z, A-Z, 0-9) and punctuation (. - :). They cannot contain spaces or other characters.
I moved "characters" to the end (of all of these types of messages). See if it's more clear.

2022-10-11 21:44 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Configure Rules on Message Exchanges to Route Messages
I agree with Dani.

2022-10-11 21:49 UTC, hannanelson commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Configure Rules on Message Exchanges to Route Messages
@danieldatri - Do you mean here?
https://docs.mulesoft.com/anypoint-mq-connector/3.x/

2022-10-11 21:55 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-routing-rules.adoc
> += Configure Rules on Message Exchanges to Route Messages
In addition to the Connector documentation, maybe we should include a note in this [requirements section](https://beta.docs.mulesoft.com/beta-mq/mq/mq-routing-rules#intelligent-routing-restrictions) as well just to be sure that customers don't miss this. We will end up getting support cases otherwise. Thoughts?

2022-10-11 23:49 UTC, GouthamiKondakindi commented on modules/ROOT/pages/_partials/mq-user-props.adoc
> +To create routing rules on numeric property values,
Pasting comment from a related PR here:
Instead of saying latest version of MQ Connector, we should include a specific version number to avoid confusion. Somal is in the process of releasing a Connector version in the next couple days. We can update the version number in the doc then.

2022-10-12 00:08 UTC, GouthamiKondakindi commented on modules/ROOT/pages/_partials/mq-user-props.adoc
> +To create routing rules on numeric property values,
Customers don't need to upgrade to latest version of MQ Connector if they're just using consumer.. they only need to upgrade if they use Connector to publish as well. 
How about something along these lines?
"If you create routing rules on numeric property values and if you use Anypoint MQ Connector to publish messages, you must upgrade to the latest version of Anypoint MQ Connector. Previous versions .... "

2022-10-12 00:12 UTC, GouthamiKondakindi commented on modules/ROOT/pages/mq-exchanges.adoc
> +[NOTE]
@hannanelson we should remove this NOTE. The message sender UI is independent of the restrictions for message routing feature. User can use any special characters for property name and value even if they have some routing rules configured on the exchange.

2022-10-12 00:30 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +Any changes or additions to a message routing rule can take up to 15 minutes to take effect.
See note above: The new message routing rule can take up to 15 minutes to take effect.

2022-10-12 01:07 UTC, GouthamiKondakindi submitted a review, later dismissed
LGTM 🥳

2022-10-12 05:35 UTC, GouthamiKondakindi approved these changes, later dismissed
LGTM

2022-10-12 16:35 UTC, IsaacEldridge commented on modules/ROOT/pages/_partials/mq-faq.adoc
> +The `headers`and `properties` of messages sent to exchanges and queues are not encrypted.
```suggestion
Anypoint MQ does not encrypt the `headers`and `properties` of messages sent to exchanges and queues.
```

2022-10-12 16:52 UTC, IsaacEldridge commented on modules/ROOT/pages/mq-routing-rules.adoc
> +To send messages to an exchange and route them to specific queues,
I'm not a fan of the way this presents on the page, as I find it visually confusing. I'd use some other method, like a two item list of choices

2022-10-12 17:02 UTC, IsaacEldridge approved these changes

2022-10-12 21:52 UTC, danieldatri approved these changes
LGTM

2022-10-18 17:43 UTC, closed without merging

2022-10-18 17:44 UTC, hannanelson commented
See #118