DOCS-4234 update
mulesoft/docs-mq pull request #26
Opened 2019-02-22 16:45 UTC by george-hoffer

2019-02-22 23:38 UTC, jjayakumaran requested changes

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1/organizations/<org_ID>/environments/<env_ID>/regions/us-east-1
this URL should be changed to https://anypoint.mulesoft.com/

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1/organizations/<org_ID>/environments/<env_ID>/regions/us-east-1
this URL should be changed to https://anypoint.mulesoft.com/

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +https://localhost:8080/api/v1/organizations/<org_ID>/environments/<env_ID>/regions/us-east-1
this URL should be changed to https://anypoint.mulesoft.com/

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +Anypoint MQ uses the Mule Analytics service to store usage metric data. The Stats API can be used to sum up the usage for Anypoint MQ across all environments for a particular organization. This is no
this need not be part of public docs. Remove the part about Analytics service.

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1  /organizations/<org_ID>/environments/<env_ID>
this URL should be changed to https://anypoint.mulesoft.com/

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +The `period` duration supports these values:
These are part of our raml docs already. And we need not add such api specifications on public tutorial. I think we can remove this.

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +Anypoint MQ uses the Mule Analytics service to store usage metric data for an organization. The Stats API can be used to sum up the usage for Anypoint MQ across the master business organization:
remove info about analytics service

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1
this URL should be changed to https://anypoint.mulesoft.com/

2019-02-22 23:38 UTC, jjayakumaran commented on modules/ROOT/pages/mq-apis.adoc
> +The `period` duration supports these values:
need not be added on public documentation

2019-02-23 00:00 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1/organizations/<org_ID>/environments/<env_ID>/regions/us-east-1
Fixed throughout

2019-02-23 00:03 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +Anypoint MQ uses the Mule Analytics service to store usage metric data. The Stats API can be used to sum up the usage for Anypoint MQ across all environments for a particular organization. This is no
Fixed

2019-02-23 00:03 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1  /organizations/<org_ID>/environments/<env_ID>
Fixed

2019-02-23 00:04 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +Anypoint MQ uses the Mule Analytics service to store usage metric data for an organization. The Stats API can be used to sum up the usage for Anypoint MQ across the master business organization:
Fixed

2019-02-23 00:08 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +http://localhost:8080/api/v1
Fixed

2019-02-23 00:08 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +The `period` duration supports these values:
Removed

2019-02-23 00:08 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +The `period` duration supports these values:
Removed

2019-03-01 02:59 UTC, steveCluster commented on modules/ROOT/pages/mq-apis.adoc
> +To use this API, you can get the access token from the Anypoint Platform user. The access token is also known as the Bearer.
can you add this here: To access the Anypoint MQ Stats API, you must first authenticate using the Anypoint Access Management API

The part where it says Anypoint Access Management API should be a link to this url: https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/

2019-03-01 03:00 UTC, steveCluster commented on modules/ROOT/pages/mq-apis.adoc
> +https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-stats/[Statistics API] - Perform statistical analysis of queue perf
Instead of using actual org and env IDs can you put in placeholders like ORGANIZATION_ID and ENVIRONMENT_ID

2019-03-05 18:49 UTC, jjayakumaran approved these changes
Please fix Steve's comments before merge. Thanks

2019-03-13 16:09 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +To use this API, you can get the access token from the Anypoint Platform user. The access token is also known as the Bearer.
Fixed as requested

2019-03-13 16:10 UTC, george-hoffer commented on modules/ROOT/pages/mq-apis.adoc
> +https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/anypoint-mq-stats/[Statistics API] - Perform statistical analysis of queue perf
Done.

2019-03-19 02:27 UTC, merged