Added large payload note, new API parameter
mulesoft/docs-mq pull request #76
Opened 2021-04-08 00:32 UTC by hannanelson

2021-04-09 18:37 UTC, danieldatri requested changes
Hi Hanna,
take a look of the comment I added. Other than that the rest seems to be fine to me.

2021-04-09 18:37 UTC, danieldatri commented on modules/ROOT/pages/_partials/mq-big-payload.adoc
> +You can retrieve them with the Anypoint Broker API.
Wouldn't be better if we attach the screenshot with the warning message the user can get on the UI for this case?

2021-04-09 18:43 UTC, hannanelson commented on modules/ROOT/pages/_partials/mq-big-payload.adoc
> +You can retrieve them with the Anypoint Broker API.
@danieldatri - the error message seems pretty self-explanatory, so I don't think we need to have a screenshot of it.

2021-04-09 18:53 UTC, kimayap03 commented on modules/ROOT/pages/mq-apis.adoc
> +"https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/42544254-4254-4254-4254-425442544254/environments/42544254-4254-4254-4254-425442544254/destinations/postmanQueue/messages?pollingTime=
Can you add the `payloadVisibility` parameter n the example query as well?

2021-04-09 18:55 UTC, kimayap03 commented on modules/ROOT/pages/mq-apis.adoc
> +"https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/42544254-4254-4254-4254-425442544254/environments/42544254-4254-4254-4254-425442544254/destinations/postmanQueue/messages?pollingTime=
We should also report `payloadHidden=true` in the response when message is hidden

2021-04-09 19:01 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +"https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/42544254-4254-4254-4254-425442544254/environments/42544254-4254-4254-4254-425442544254/destinations/postmanQueue/messages?pollingTime=
@kimayap03 - updated with your comments.

2021-04-09 19:42 UTC, kimayap03 commented on modules/ROOT/pages/mq-apis.adoc
> +If the value of `payloadVisibility` is `none`, the response includes `payloadHidden=true` in the header.
though this statement is true, it doesnt offer complete information. 
Can we rephrase it to say something like If payload is hidden as a result of param value `none` or `conditional`, response will include`payloadHidden=true` in the message header.

2021-04-09 19:44 UTC, kimayap03 commented on modules/ROOT/pages/mq-apis.adoc
> +The following curl command gets a message and displays the payload only if the size is smaller than 1 MB:
this gives illusion that we will not retrieve the message if payload is < 1MB, where as curl command response will still `get` the message

2021-04-09 20:21 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +If the value of `payloadVisibility` is `none`, the response includes `payloadHidden=true` in the header.
Clarified.

2021-04-09 20:27 UTC, kimayap03 approved these changes, later dismissed
LGTM!

2021-04-09 22:24 UTC, prafulrana approved these changes, later dismissed

2021-04-09 22:28 UTC, dukesphere reviewed
some suggestions

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +These examples use the Anypoint MQ Broker API to publish and consume messages and test Anypoint MQ from the command line using curl.
```suggestion
These examples use the Anypoint MQ Broker API to publish and consume messages and to test Anypoint MQ from the command line using curl.
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +You must substitute the placeholder string, `42544254-4254-4254-4254-425442544254` for the proper values for authorization and token strings. These examples use Postman to access the queue.
```suggestion
You must substitute the placeholder string, `42544254-4254-4254-4254-425442544254` with the proper values for authorization and token strings. These examples use Postman to access the queue.
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +The following *curl* command publishes a message:
```suggestion
The following `curl` command publishes a message:
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +The following curl command gets a message:
```suggestion
The following `curl` command gets a message:
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +* `full`: Shows the message payload in the response+
```suggestion
* `full`: Shows the message payload in the response. +
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +* `none`: Hides the message payload in the response
```suggestion
* `none`: Hides the message payload in the response.
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +The following curl command gets a message and payload, displaying the payload only if the payload size is smaller than 1 MB:
```suggestion
The following `curl` command gets a message and payload, displaying the payload only if the payload size is smaller than 1 MB:
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +To download the Anypoint MQ APIs from Exchange, click *Download* and select the format to download: RAML, OAS, or as a connector file for Mule 3 or Mule 4.
minor: "as a" sounds kind of odd, but I don't have a good alternative.

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +.The arrow shows the *Download* button in Exchange.
```suggestion
.The arrow shows the *Download* button in Exchange:
```

2021-04-09 22:28 UTC, dukesphere commented on modules/ROOT/pages/mq-apis.adoc
> +.The arrow shows the *Download* button in Exchange.
Your call. I like colons on these because of the way the captions look in HTML. It's not always clear that they are captions for something that comes next. Same goes for the next one(s).

2021-04-09 22:37 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +.The arrow shows the *Download* button in Exchange.
I don't put the colon on captions because I put them in the intro sentence (per Kim style).

2021-04-09 22:38 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +To download the Anypoint MQ APIs from Exchange, click *Download* and select the format to download: RAML, OAS, or as a connector file for Mule 3 or Mule 4.
Stole that sentence from a Kim-approved version in OSv2...

2021-04-09 22:38 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +* `none`: Hides the message payload in the response
Not a complete sentence, so leaving.

2021-04-09 22:39 UTC, dukesphere submitted a review, later dismissed

2021-04-09 22:41 UTC, hannanelson commented on modules/ROOT/pages/mq-apis.adoc
> +* `none`: Hides the message payload in the response
nm, implemented.

2021-04-09 22:42 UTC, dukesphere submitted a review, later dismissed

2021-04-09 23:50 UTC, danieldatri approved these changes, later dismissed
LGTM

2021-04-12 23:41 UTC, danieldatri requested changes

2021-04-12 23:41 UTC, danieldatri commented on modules/ROOT/pages/mq-faq.adoc
> +The *Message Browser* page displays the payload only if the payload size is smaller that 1 MB.
Shouldn't be say **smaller than** instead of **smaller that**?
If I'm wrong I was wrong my hole life thinking  that was the correct wait to say it.  :)

2021-04-13 00:40 UTC, hannanelson commented on modules/ROOT/pages/mq-faq.adoc
> +The *Message Browser* page displays the payload only if the payload size is smaller that 1 MB.
You're RIGHT. Typo!

2021-04-13 00:43 UTC, hannanelson commented on modules/ROOT/pages/mq-faq.adoc
> +The *Message Browser* page displays the payload only if the payload size is smaller that 1 MB.
Fixed in the RN PR too.

2021-04-14 20:55 UTC, danieldatri approved these changes
LGTM

2021-04-14 23:27 UTC, dukesphere approved these changes

2021-04-27 14:44 UTC, merged